### ISSUE TITLE
Rounding in Python

### ISSUE THREAD

**Issue by Yukti-09** [satwikkansal/wtfpython#217] opened 2020-08-04 04:42 UTC
Code:
```
print (round(3.555, 2))
print (round(2.555, 2))  
print (round(1.555, 2))
```
Output:
```
3.56
2.56                                                                                                                    
1.55                                                                                                                
        
```
Why doesn't round(1.555, 2) give 1.56 as the output?

**Comment by satwikkansal** [comment] 2020-08-04 16:44
Duplicate of https://github.com/satwikkansal/wtfpython/issues/196

**Closed by satwikkansal** 2020-08-04 16:44 UTC
