### ISSUE TITLE
Prehistory

### ISSUE THREAD

**Issue by MarcinCiura** [satwikkansal/wtfpython#206] opened 2020-05-22 09:35 UTC
Hi Satwik! If you are interested in antediluvian times, check out https://github.com/MarcinCiura/6-gotchas :)
Cheers!

**Comment by satwikkansal** [comment] 2020-06-09 13:54
Oh nice, I was wondering what to do today, and I found this :)

**Comment by nifadyev** [comment] 2024-10-09 08:21
Hey @satwikkansal , link is dead and the issue is not related to project. Maybe close this one?

**Closed** 2024-10-11 11:46 UTC
